const PoSPoolABI =  [
  "event ClaimInterest(address indexed,uint256)",
  "event DecreasePoSStake(address indexed,uint256)",
  "event IncreasePoSStake(address indexed,uint256)",
  "event OwnershipTransferred(address indexed,address indexed)",
  "event RatioChanged(uint256)",
  "event WithdrawStake(address indexed,uint256)",
  "function _poolLockPeriod() view returns (uint256)",
  "function _poolRegisted() view returns (bool)",
  "function _posAddressToIdentifier(address) view returns (bytes32)",
  "function _posRegisterIncreaseStake(uint64)",
  "function _posRegisterRegister(bytes32,uint64,bytes,bytes,bytes[2])",
  "function _posRegisterRetire(uint64)",
  "function _retireUserStake(address,uint64)",
  "function _retireUserStakes(uint256,uint256,uint64)",
  "function _stakingDeposit(uint256)",
  "function _stakingWithdraw(uint256)",
  "function _withdrawPoolProfit(uint256)",
  "function accRewardPerCfx() view returns (uint256)",
  "function claimAllInterest()",
  "function claimInterest(uint256)",
  "function decreaseStake(uint64)",
  "function increaseStake(uint64) payable",
  "function initialize()",
  "function owner() view returns (address)",
  "function poolAPY() view returns (uint256)",
  "function poolName() view returns (string)",
  "function poolSummary() view returns (tuple(uint256,uint256,uint256))",
  "function poolUserShareRatio() view returns (uint256)",
  "function posAddress() view returns (bytes32)",
  "function reStake(uint64)",
  "function register(bytes32,uint64,bytes,bytes,bytes[2]) payable",
  "function renounceOwnership()",
  "function setCfxCountOfOneVote(uint256)",
  "function setLockPeriod(uint64)",
  "function setPoolName(string)",
  "function setPoolUserShareRatio(uint64)",
  "function stakerAddress(uint256) view returns (address)",
  "function stakerNumber() view returns (uint256)",
  "function transferOwnership(address)",
  "function userInQueue(address,uint64,uint64) view returns (tuple(uint256,uint256)[])",
  "function userInQueue(address) view returns (tuple(uint256,uint256)[])",
  "function userInterest(address) view returns (uint256)",
  "function userOutQueue(address) view returns (tuple(uint256,uint256)[])",
  "function userOutQueue(address,uint64,uint64) view returns (tuple(uint256,uint256)[])",
  "function userSummary(address) view returns (tuple(uint256,uint256,uint256,uint256,uint256,uint256))",
  "function withdrawStake(uint64)",
  "function userShareRatio(address) view returns (uint256)"
];

const PoSNFTABI = ['function balanceOf(address) view returns (uint256)'];